name: look_mood
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.1
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  http: ^1.2.3
  provider: ^6.1.5
  cached_network_image: ^3.2.3
  flutter_rating_bar: 4.0.1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  dart_openai: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/img/
  - assets/roupas/